give warning on non-existent bib-file

diff --git a/create_pages b/create_pages
--- a/create_pages
+++ b/create_pages
@@ -23,10 +23,14 @@ do
     if [ -f publications/$CATEGORY.bib ]
     then
 	bibtex2html -nokeys -nofooter -nodoc -dl -d -r -q -o generated_publications_$CATEGORY publications/$CATEGORY.bib
+    else
+	echo "Warning: publications/$CATEGORY.bib is missing" 1>&2
     fi
 
     if [ -f talks/$CATEGORY.bib ]
     then
 	bibtex2html -nokeys -nofooter -nodoc -nf ppt ".ppt" -dl -d -r -q -o generated_talks_$CATEGORY talks/$CATEGORY.bib
+    else
+	echo "Warning: talks/$CATEGORY.bib is missing" 1>&2
     fi
 done
